import bcryptjs from "bcryptjs";

interface SeedProduct {
  description: string;
  images: string[];
  inStock: number;
  price: number;
  sizes: ValidSizes[];
  slug: string;
  tags: string[];
  title: string;
  type: ValidTypes;
  gender: "men" | "women" | "kid" | "unisex";
}

interface SeedUser {
  email: string;
  password: string;
  name: string;
  role: "admin" | "user";
}

type ValidSizes = "XS" | "S" | "M" | "L" | "XL" | "XXL" | "XXXL";
type ValidTypes = "shirts" | "pants" | "hoodies" | "hats";

interface SeedData {
  users: SeedUser[];
  categories: string[];
  products: SeedProduct[];
}

export const initialData: SeedData = {
  users: [
    {
      email: "franciscobenegas@gmail.com",
      name: "Francisco Benegas",
      password: bcryptjs.hashSync("admin123"),
      role: "admin",
    },
    {
      email: "lili@google.com",
      name: "Liliana Lopez",
      password: bcryptjs.hashSync("123456"),
      role: "user",
    },
  ],

  categories: ["Shirts", "Pants", "Hoodies", "Hats"],
  products: [
    {
      description:
        "Presentamos la colección Tesla Chill. La sudadera Chill con cuello redondo para hombre tiene un exterior pesado de primera calidad y un interior de tejido polar suave para brindar comodidad en cualquier época del año. La sudadera presenta un sutil logotipo T de poliuretano termoplástico en el pecho y una marca denominativa Tesla debajo del cuello trasero. Confeccionada con 60% algodón y 40% poliéster reciclado.",
      images: ["1740176-00-A_0_2000.jpg", "1740176-00-A_1.jpg"],
      inStock: 7,
      price: 75,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "sudadera_chill_de_cuello_redondo_para_hombre",
      type: "shirts",
      tags: ["sweatshirt"],
      title: "Sudadera Chill de cuello redondo para hombre",
      gender: "men",
    },
    {
      description:
        "La chaqueta camisera acolchada para hombre presenta un diseño acolchado de ajuste único para brindar calidez y movilidad en las estaciones de clima frío. Con una estética urbana general, la chaqueta presenta sutiles logotipos de Tesla inyectados con silicona debajo del cuello trasero y en la manga derecha, así como tiradores de cremallera de metal mate personalizados. Fabricado con 87% nailon y 13% poliuretano.",
      images: ["1740507-00-A_0_2000.jpg", "1740507-00-A_1.jpg"],
      inStock: 5,
      price: 200,
      sizes: ["XS", "S", "M", "XL", "XXL"],
      slug: "chaqueta_camisera_acolchada_para_hombre",
      type: "shirts",
      tags: ["jacket"],
      title: "Chaqueta camisera acolchada para hombre",
      gender: "men",
    },

    {
      description:
        "Presentamos la colección Tesla Raven. La cazadora bomber ligera con cremallera Raven para hombre tiene una silueta moderna y de primera calidad confeccionada con una mezcla de algodón de bambú sostenible para brindar versatilidad en cualquier temporada. La sudadera con capucha presenta sutiles logotipos de Tesla de poliuretano termoplástico en el lado izquierdo del pecho y debajo del cuello trasero, un bolsillo oculto en el pecho con tiradores de cremallera mate personalizados y un interior de felpa francesa. Fabricada en 70% bambú y 30% algodón.",
      images: ["1740250-00-A_0_2000.jpg", "1740250-00-A_1.jpg"],
      inStock: 10,
      price: 130,
      sizes: ["S", "M", "L", "XL", "XXL"],
      slug: "chaqueta_bomber_ligera_con_cremallera_raven_para_hombre",
      type: "shirts",
      tags: ["shirt"],
      title: "Chaqueta bomber ligera con cremallera Raven para hombret",
      gender: "men",
    },

    {
      description:
        "Presentamos la colección de turbinas Tesla. Diseñada para brindar estilo, comodidad y estilo de vida cotidiano, la camiseta de manga larga Turbine para hombre presenta un sutil logotipo T a base de agua en el lado izquierdo del pecho y nuestra marca Tesla debajo del cuello trasero. El material liviano está teñido doblemente, lo que crea un estilo suave e informal ideal para usar en cualquier época del año. Confeccionada en 50% algodón y 50% poliéster.",
      images: ["1740280-00-A_0_2000.jpg", "1740280-00-A_1.jpg"],
      inStock: 50,
      price: 45,
      sizes: ["XS", "S", "M", "L"],
      slug: "camiseta_de_manga_larga_turbine_para_hombre",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta de manga larga Turbine para hombre",
      gender: "men",
    },
    {
      description:
        "Presentamos la colección de turbinas Tesla. Diseñada para brindar estilo, comodidad y estilo de vida cotidiano, la camiseta de manga corta Turbine para hombre presenta una sutil marca denominativa Tesla a base de agua en el pecho y nuestro logotipo T debajo del cuello trasero. El material liviano está teñido doblemente, lo que crea un estilo suave e informal ideal para usar en cualquier época del año. Confeccionada en 50% algodón y 50% poliéster.",
      images: ["1741416-00-A_0_2000.jpg", "1741416-00-A_1.jpg"],
      inStock: 50,
      price: 40,
      sizes: ["M", "L", "XL", "XXL"],
      slug: "camiseta_de_manga_corta_turbine_para_hombre",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta de manga corta Turbine para hombre",
      gender: "men",
    },
    {
      description:
        "Diseñada para brindar comodidad, la camiseta Cybertruck Owl está hecha de 100% algodón y presenta nuestro ícono Cybertruck característico en la parte posterior.",
      images: ["7654393-00-A_2_2000.jpg", "7654393-00-A_3.jpg"],
      inStock: 0,
      price: 35,
      sizes: ["M", "L", "XL", "XXL"],
      slug: "camiseta_cybertruck_owl_para_hombre",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta Cybertruck Owl para hombre",
      gender: "men",
    },
    {
      description:
        "Inspirado en nuestro sistema de almacenamiento y energía solar doméstico totalmente integrado, el Tesla Solar Roof Tee aboga por una energía limpia y sostenible dondequiera que vaya. Diseñada para brindar ajuste, comodidad y estilo, la camiseta presenta una vista aérea de nuestro diseño Solar Roof sin costuras en la parte delantera con nuestro logotipo T característico sobre Solar Roof en la parte posterior. Confeccionada en 100% algodón peruano.",
      images: ["1703767-00-A_0_2000.jpg", "1703767-00-A_1.jpg"],
      inStock: 15,
      price: 35,
      sizes: ["S", "M", "L", "XL"],
      slug: "camiseta_con_techo_solar_para_hombre",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta con techo solar para hombre",
      gender: "men",
    },
    {
      description:
        "Inspirada en el recurso más ilimitado del mundo, la camiseta Let the Sun Shine destaca nuestro sistema de almacenamiento y energía solar doméstico totalmente integrado. Diseñada para brindar ajuste, comodidad y estilo, la camiseta presenta un gráfico de una puesta de sol junto con nuestra marca denominativa Tesla en el frente y nuestro logotipo T impreso sobre Solar Roof en la parte posterior. Confeccionada en 100% algodón peruano.",
      images: ["1700280-00-A_0_2000.jpg", "1700280-00-A_1.jpg"],
      inStock: 17,
      price: 35,
      sizes: ["XS", "S", "XL", "XXL"],
      slug: "camiseta_let_the_sun_shine_para_hombre",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta Let the Sun Shine para hombre",
      gender: "men",
    },
    {
      description:
        "Diseñada para ofrecer ajuste, comodidad y estilo, la camiseta 3D Large Wordmark para hombre está confeccionada con 100 % algodón peruano y tiene la marca Tesla impresa en silicona 3D en el pecho.",
      images: ["8764734-00-A_0_2000.jpg", "8764734-00-A_1.jpg"],
      inStock: 12,
      price: 35,
      sizes: ["XS", "S", "M"],
      slug: "camiseta_con_logo_grande_en_3d_para_hombre",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta con logo grande en 3D para hombre",
      gender: "men",
    },
    {
      description:
        "Diseñada para brindar ajuste, comodidad y estilo, la camiseta Tesla T Logo está hecha de 100% algodón peruano y presenta un logotipo T impreso en silicona en el pecho izquierdo.",
      images: ["7652426-00-A_0_2000.jpg", "7652426-00-A_1.jpg"],
      inStock: 5,
      price: 35,
      sizes: ["XS", "S"],
      slug: "camiseta_con_logotipo_3d_t_para_hombre",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta con logotipo 3D T para hombre",
      gender: "men",
    },
    {
      description:
        "Diseñada para ofrecer comodidad y estilo en cualquier talla, la camiseta Tesla Small Wordmark está confeccionada con 100 % algodón peruano y presenta una marca denominativa impresa en silicona 3D en el lado izquierdo del pecho.",
      images: ["8528839-00-A_0_2000.jpg", "8528839-00-A_2.jpg"],
      inStock: 2,
      price: 35,
      sizes: ["XS", "S", "M"],
      slug: "camiseta_con_marca_denominativa_pequena_en_3d_para_hombre",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta con marca denominativa pequeña en 3D para hombre",
      gender: "men",
    },
    {
      description:
        "Diseñada para celebrar el increíble modo de rendimiento de Tesla, la camiseta Plaid Mode presenta un gran ajuste, comodidad y estilo. Hecho de 100% algodón, es lo mejor después de montar a caballo en Nürburgring.",
      images: ["1549268-00-A_0_2000.jpg", "1549268-00-A_2.jpg"],
      inStock: 82,
      price: 35,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "camiseta_a_cuadros_para_hombre",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta a cuadros para hombre",
      gender: "men",
    },
    {
      description:
        "Inspirada en nuestra popular batería doméstica, la camiseta Tesla Powerwall está hecha de 100% algodón y presenta la frase Pure Energy debajo de nuestro logo en la parte posterior. Diseñada para ofrecer ajuste, comodidad y estilo, la camiseta exclusiva promueve la energía sostenible en cualquier entorno.",
      images: ["9877034-00-A_0_2000.jpg", "9877034-00-A_2.jpg"],
      inStock: 24,
      price: 35,
      sizes: ["XL", "XXL"],
      slug: "camiseta_powerwall_para_hombre",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta Powerwall para hombre",
      gender: "men",
    },
    {
      description:
        "Inspirada en el Día de la Batería de Tesla y presentando la celda de batería sin mesa presentada, la camiseta Battery Day celebra el futuro del almacenamiento de energía y la fabricación de celdas. Diseñada para brindar ajuste, comodidad y estilo, la camiseta Battery Day está confeccionada con 100 % algodón y tiene una celda estilizada impresa en el pecho. Hecho en Paraguay.",
      images: ["1633802-00-A_0_2000.jpg", "1633802-00-A_2.jpg"],
      inStock: 5,
      price: 30,
      sizes: ["XS", "S", "XXL"],
      slug: "camiseta_del_dia_de_la_bateria_para_hombre",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta del día de la batería para hombre",
      gender: "men",
    },
    {
      description:
        "Designed for exceptional comfort and inspired by the Cybertruck unveil event, the Cybertruck Bulletproof Tee is made from 100% cotton and features our signature Cybertruck icon on the back.",
      images: ["7654399-00-A_0_2000.jpg", "7654399-00-A_1.jpg"],
      inStock: 150,
      price: 30,
      sizes: ["M", "L"],
      slug: "men_cybertruck_bulletproof_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men’s Cybertruck Bulletproof Tee",
      gender: "men",
    },
    {
      description:
        "Inspired by the Model Y order confirmation graphic, the limited edition Haha Yes Tee is designed for comfort and style. Made from 100% Peruvian cotton and featuring the Tesla wordmark across the chest, the exclusive tee will commemorate your order for years to come.",
      images: ["7652410-00-A_0.jpg", "7652410-00-A_1_2000.jpg"],
      inStock: 10,
      price: 35,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "men_haha_yes_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's Haha Yes Tee",
      gender: "men",
    },
    {
      description:
        "Diseñada para brindar ajuste, comodidad y estilo, la camiseta S3XY de edición limitada está hecha de 100% algodón con un logotipo S3XY impreso en silicona 3D en el pecho. Hecho en Paraguay. Disponible en negro.",
      images: ["8764600-00-A_0_2000.jpg", "8764600-00-A_2.jpg"],
      inStock: 34,
      price: 35,
      sizes: ["XS", "S", "M", "L"],
      slug: "camiseta_s3xy_para_hombre",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta S3XY para hombre",
      gender: "men",
    },
    {
      description:
        "Designed for fit, comfort and style, the Men's 3D Wordmark Long Sleeve Tee is made from 100% cotton and features an understated wordmark logo on the left chest.",
      images: ["8764813-00-A_0_2000.jpg", "8764813-00-A_1.jpg"],
      inStock: 15,
      price: 40,
      sizes: ["XL", "XXL"],
      slug: "men_3d_wordmark_long_sleeve_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's 3D Wordmark Long Sleeve Tee",
      gender: "men",
    },
    {
      description:
        "Designed for fit, comfort and style, the Men's 3D T Logo Long Sleeve Tee is made from 100% cotton and features an understated T logo on the left chest.",
      images: ["8529198-00-A_0_2000.jpg", "8529198-00-A_1.jpg"],
      inStock: 12,
      price: 40,
      sizes: ["XS", "XXL"],
      slug: "men_3d_t_logo_long_sleeve_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's 3D T Logo Long Sleeve Tee",
      gender: "men",
    },
    {
      description:
        "Introducing the Tesla Raven Collection. The Men's Raven Lightweight Hoodie has a premium, relaxed silhouette made from a sustainable bamboo cotton blend. The hoodie features subtle thermoplastic polyurethane Tesla logos across the chest and on the sleeve with a french terry interior for versatility in any season. Made from 70% bamboo and 30% cotton.",
      images: ["1740245-00-A_0_2000.jpg", "1740245-00-A_1.jpg"],
      inStock: 10,
      price: 115,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "men_raven_lightweight_hoodie",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Men's Raven Lightweight Hoodie",
      gender: "men",
    },
    {
      description:
        "Introducing the Tesla Chill Collection. The Chill Pullover Hoodie has a premium, heavyweight exterior and soft fleece interior for comfort in any season. The unisex hoodie features subtle thermoplastic polyurethane Tesla logos across the chest and on the sleeve, a double layer single seam hood and pockets with custom matte zipper pulls. Made from 60% cotton and 40% recycled polyester.",
      images: ["1740051-00-A_0_2000.jpg", "1740051-00-A_1.jpg"],
      inStock: 10,
      price: 130,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "chill_pullover_hoodie",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Chill Pullover Hoodie",
      gender: "unisex",
    },
    {
      description:
        "Introducing the Tesla Chill Collection. The Men's Chill Full Zip Hoodie has a premium, heavyweight exterior and soft fleece interior for comfort in any season. The hoodie features subtle thermoplastic polyurethane Tesla logos on the left chest and sleeve, a double layer single seam hood and pockets with custom matte zipper pulls. Made from 60% cotton and 40% recycled polyester.",
      images: ["1741111-00-A_0_2000.jpg", "1741111-00-A_1.jpg"],
      inStock: 100,
      price: 85,
      sizes: ["XS", "L", "XL", "XXL"],
      slug: "men_chill_full_zip_hoodie",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's Chill Full Zip Hoodie",
      gender: "men",
    },
    {
      description:
        "Introducing the Tesla Chill Collection. The Men’s Chill Quarter Zip Pullover has a premium, heavyweight exterior and soft fleece interior for comfort in any season. The pullover features subtle thermoplastic polyurethane Tesla logos on the left chest and below the back collar, as well as a custom matte zipper pull. Made from 60% cotton and 40% recycled polyester.",
      images: ["1740140-00-A_0_2000.jpg", "1740140-00-A_1.jpg"],
      inStock: 7,
      price: 85,
      sizes: ["XS", "S", "M"],
      slug: "men_chill_quarter_zip_pullover_-_gray",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's Chill Quarter Zip Pullover - Gray",
      gender: "men",
    },
    {
      description:
        "Presentamos la colección Tesla Chill. El jersey Chill Quarter Zip para hombre tiene un exterior pesado de primera calidad y un interior de tejido polar suave para mayor comodidad en cualquier época del año. El jersey presenta sutiles logotipos de Tesla de poliuretano termoplástico en el lado izquierdo del pecho y debajo del cuello trasero, así como un tirador de cremallera mate personalizado. Confeccionada con 60% algodón y 40% poliéster reciclado.",
      images: ["1740145-00-A_2_2000.jpg", "1740145-00-A_1.jpg"],
      inStock: 15,
      price: 85,
      sizes: ["XS", "S", "M", "L"],
      slug: "jersey_chill_con_cremallera_de_un_cuarto_para_hombre_blanco",
      type: "shirts",
      tags: ["shirt"],
      title: "Jersey Chill con cremallera de un cuarto para hombre - Blanco",
      gender: "men",
    },
    {
      description:
        "The Unisex 3D Large Wordmark Pullover Hoodie features soft fleece and an adjustable, jersey-lined hood for comfort and coverage. Designed in a unisex style, the pullover hoodie includes a tone-on-tone 3D silicone-printed wordmark across the chest.",
      images: ["8529107-00-A_0_2000.jpg", "8529107-00-A_1.jpg"],
      inStock: 15,
      price: 70,
      sizes: ["XS", "S", "XL", "XXL"],
      slug: "3d_large_wordmark_pullover_hoodie",
      type: "hoodies",
      tags: ["hoodie"],
      title: "3D Large Wordmark Pullover Hoodie",
      gender: "unisex",
    },
    {
      description:
        "As with the iconic Tesla logo, the Cybertruck Graffiti Hoodie is a classic in the making. Unisex style featuring soft fleece and an adjustable, jersey-lined hood for comfortable coverage.",
      images: ["7654420-00-A_0_2000.jpg", "7654420-00-A_1_2000.jpg"],
      inStock: 13,
      price: 60,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "cybertruck_graffiti_hoodie",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Cybertruck Graffiti Hoodie",
      gender: "unisex",
    },
    {
      description:
        "The Relaxed T Logo Hat is a classic silhouette combined with modern details, featuring a 3D T logo and a custom metal buckle closure. The ultrasoft design is flexible and abrasion resistant, while the inner sweatband includes quilted padding for extra comfort and moisture wicking. The visor is fully made from recycled plastic bottles. 100% Cotton.",
      images: ["1657932-00-A_0_2000.jpg", "1657932-00-A_1.jpg"],
      inStock: 11,
      price: 30,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "relaxed_t_logo_hat",
      type: "hats",
      tags: ["hats"],
      title: "Relaxed T Logo Hat",
      gender: "unisex",
    },
    {
      description:
        "The Relaxed T Logo Hat is a classic silhouette combined with modern details, featuring a 3D T logo and a custom metal buckle closure. The ultrasoft design is flexible and abrasion resistant, while the inner sweatband includes quilted padding for extra comfort and moisture wicking. The visor is fully made from recycled plastic bottles. 100% Cotton.",
      images: ["1740417-00-A_0_2000.jpg", "1740417-00-A_1.jpg"],
      inStock: 13,
      price: 35,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "thermal_cuffed_beanie",
      type: "hats",
      tags: ["hats"],
      title: "Thermal Cuffed Beanie",
      gender: "unisex",
    },
    {
      description:
        "La chaqueta acolchada recortada para mujer presenta una silueta recortada única para un estilo perfecto y moderno mientras estás en movimiento durante la acogedora temporada que se avecina. La chaqueta acolchada presenta sutiles logotipos de Tesla inyectados con silicona debajo del cuello trasero y en la manga derecha, tiradores de cremallera de metal mate personalizados y un cuello suave con forro polar. Fabricado con 87% nailon y 13% poliuretano.",
      images: ["1740535-00-A_0_2000.jpg", "1740535-00-A_1.jpg"],
      inStock: 85,
      price: 225,
      sizes: ["XS", "S", "M"],
      slug: "chaqueta_acolchada_corta_para_mujer",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Chaqueta acolchada corta para mujer",
      gender: "women",
    },
    {
      description:
        "Introducing the Tesla Chill Collection. The Women's Chill Half Zip Cropped Hoodie has a premium, soft fleece exterior and cropped silhouette for comfort in everyday lifestyle. The hoodie features an elastic hem that gathers at the waist, subtle thermoplastic polyurethane Tesla logos along the hood and on the sleeve, a double layer single seam hood and a custom ring zipper pull. Made from 60% cotton and 40% recycled polyester.",
      images: ["1740226-00-A_0_2000.jpg", "1740226-00-A_1.jpg"],
      inStock: 10,
      price: 130,
      sizes: ["XS", "S", "M", "XXL"],
      slug: "women_chill_half_zip_cropped_hoodie",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Women's Chill Half Zip Cropped Hoodie",
      gender: "women",
    },
    {
      description:
        "Presentamos la colección Tesla Raven. La sudadera Raven Slouchy Crew para mujer tiene una silueta relajada y de primera calidad confeccionada con una mezcla de algodón de bambú sostenible. La camiseta holgada presenta una sutil marca Tesla de poliuretano termoplástico en la manga izquierda y un interior de felpa francesa para una apariencia y sensación acogedoras en cada temporada. Combínalo con tus Raven Joggers o tu prenda favorita para llevar. Fabricada en 70% bambú y 30% algodón.",
      images: ["1740260-00-A_0_2000.jpg", "1740260-00-A_1.jpg"],
      inStock: 9,
      price: 110,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "sudadera_raven_slouchy_crew_para_mujer",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Sudadera Raven Slouchy Crew para mujer",
      gender: "women",
    },
    {
      description:
        "Introducing the Tesla Turbine Collection. Designed for style, comfort and everyday lifestyle, the Women's Turbine Cropped Long Sleeve Tee features a subtle, water-based Tesla wordmark across the chest and our T logo below the back collar. The lightweight material is double-dyed, creating a soft, casual style with a cropped silhouette. Made from 50% cotton and 50%",
      images: ["1740290-00-A_0_2000.jpg", "1740290-00-A_1.jpg"],
      inStock: 10,
      price: 45,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "women_turbine_cropped_long_sleeve_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Women's Turbine Cropped Long Sleeve Tee",
      gender: "women",
    },
    {
      description:
        "Presentamos la colección de turbinas Tesla. Diseñada para brindar estilo, comodidad y estilo de vida cotidiano, la camiseta corta de manga corta Turbine para mujer presenta una sutil marca denominativa Tesla a base de agua en el pecho y nuestro logotipo T debajo del cuello trasero. El material ligero está teñido doblemente, lo que crea un estilo suave e informal con una silueta recortada. Confeccionada en 50% algodón y 50% poliéster.",
      images: ["1741441-00-A_0_2000.jpg", "1741441-00-A_1.jpg"],
      inStock: 0,
      price: 40,
      sizes: ["XS", "S"],
      slug: "camiseta_corta_de_manga_corta_turbine_para_mujer",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta corta de manga corta Turbine para mujer",
      gender: "women",
    },
    {
      description:
        "Designed for style and comfort, the ultrasoft Women's T Logo Short Sleeve Scoop Neck Tee features a tonal 3D silicone-printed T logo on the left chest. Made of 50% Peruvian cotton and 50% Peruvian viscose.",
      images: ["8765090-00-A_0_2000.jpg", "8765090-00-A_1.jpg"],
      inStock: 30,
      price: 35,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "women_t_logo_short_sleeve_scoop_neck_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Women's T Logo Short Sleeve Scoop Neck Tee",
      gender: "women",
    },
    {
      description:
        "Diseñada para brindar estilo y comodidad, la camiseta ultrasuave de manga larga con cuello redondo y logotipo T para mujer presenta un logotipo T tonal impreso en silicona en 3D en el pecho izquierdo. Confeccionada en 50% algodón peruano y 50% viscosa peruana.",
      images: ["8765100-00-A_0_2000.jpg", "8765100-00-A_1.jpg"],
      inStock: 16,
      price: 40,
      sizes: ["XS", "S", "L", "XL", "XXL"],
      slug: "camiseta_de_manga_larga_con_cuello_redondo_y_logo_t_para_mujer",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta de manga larga con cuello redondo y logo T para mujer",
      gender: "women",
    },
    {
      description:
        "Diseñada para brindar estilo y comodidad, la camiseta de manga corta con cuello en V Wordmark Small para mujer presenta una marca denominativa impresa en silicona 3D en el mismo tono en el lado izquierdo del pecho. Confeccionada en 100% algodón peruano.",
      images: ["8765120-00-A_0_2000.jpg", "8765120-00-A_1.jpg"],
      inStock: 18,
      price: 35,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "camiseta_de_manga_corta_con_cuello_en_v_y_logo_pequeno_para_mujer",
      type: "shirts",
      tags: ["shirt"],
      title:
        "Camiseta de manga corta con cuello en V y logo pequeño para mujer",
      gender: "women",
    },
    {
      description:
        "Designed for style and comfort, the Women's Large Wordmark Short Sleeve Crew Neck Tee features a tonal 3D silicone-printed wordmark across the chest. Made of 100% Peruvian pima cotton.",
      images: ["8765115-00-A_0_2000.jpg", "8765115-00-A_1.jpg"],
      inStock: 5,
      price: 35,
      sizes: ["XL", "XXL"],
      slug: "women_large_wordmark_short_sleeve_crew_neck_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Women's Large Wordmark Short Sleeve Crew Neck Tee",
      gender: "women",
    },
    {
      description:
        "Designed to celebrate Tesla's incredible performance mode, the Plaid Mode Tee features great fit, comfort and style. Made from 100% cotton, it's the next best thing to riding shotgun at the Nürburgring.",
      images: ["1549275-00-A_0_2000.jpg", "1549275-00-A_1.jpg"],
      inStock: 16,
      price: 35,
      sizes: ["S", "M"],
      slug: "women_plaid_mode_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Women's Plaid Mode Tee",
      gender: "women",
    },
    {
      description:
        "Inspired by our popular home battery, the Tesla Powerwall Tee is made from 100% cotton and features the phrase 'Pure Energy' under our signature logo in the back. Designed for fit, comfort and style, the exclusive tee promotes sustainable energy in any",
      images: ["9877040-00-A_0_2000.jpg", "9877040-00-A_1.jpg"],
      inStock: 10,
      price: 130,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "women_powerwall_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Women’s Powerwall Tee",
      gender: "women",
    },
    {
      description:
        "Fully customized and uniquely styled, the Women's Corp Jacket features a silicone-printed 'T' logo on the left chest and prominent Tesla wordmark across the back.",
      images: ["5645680-00-A_0_2000.jpg", "5645680-00-A_3.jpg"],
      inStock: 3,
      price: 90,
      sizes: ["M", "L", "XL", "XXL"],
      slug: "women_corp_jacket",
      type: "shirts",
      tags: ["shirt"],
      title: "Women's Corp Jacket",
      gender: "women",
    },
    {
      description:
        "Introducing the Tesla Raven Collection. The Women's Raven Joggers have a premium, relaxed silhouette made from a sustainable bamboo cotton blend. The joggers feature a subtle thermoplastic polyurethane Tesla wordmark and T logo and a french terry interior for a cozy look and feel in every season. Pair them with your Raven Slouchy Crew Sweatshirt, Raven Lightweight Zip Up Jacket or other favorite on the go fit. Made from 70% bamboo and 30% cotton.",
      images: ["1740270-00-A_0_2000.jpg", "1740270-00-A_1.jpg"],
      inStock: 162,
      price: 100,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "women_raven_joggers",
      type: "shirts",
      tags: ["shirt"],
      title: "Women's Raven Joggers",
      gender: "women",
    },
    {
      description:
        "Diseñada para brindar ajuste, comodidad y estilo, la camiseta de manga larga Cybertruck Graffiti para niños presenta una marca de graffiti Cybertruck a base de agua en el pecho, una marca de Tesla en el brazo izquierdo y nuestro logotipo T característico en la parte posterior del cuello. Confeccionada en 50% algodón y 50% poliéster.",
      images: ["1742694-00-A_1_2000.jpg", "1742694-00-A_3.jpg"],
      inStock: 10,
      price: 30,
      sizes: ["XS", "S", "M"],
      slug: "camiseta_de_manga_larga_cybertruck_para_ninos",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta de manga larga Cybertruck para niños",
      gender: "kid",
    },
    {
      description:
        "The Kids Scribble T Logo Tee is made from 100% Peruvian cotton and features a Tesla T sketched logo for every young artist to wear.",
      images: ["8529312-00-A_0_2000.jpg", "8529312-00-A_1.jpg"],
      inStock: 0,
      price: 25,
      sizes: ["XS", "S", "M"],
      slug: "kids_scribble_t_logo_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Kids Scribble T Logo Tee",
      gender: "kid",
    },
    {
      description:
        "The Kids Cybertruck Tee features the iconic Cybertruck graffiti wordmark and is made from 100% Peruvian cotton for maximum comfort.",
      images: ["8529342-00-A_0_2000.jpg", "8529342-00-A_1.jpg"],
      inStock: 10,
      price: 25,
      sizes: ["XS", "S", "M"],
      slug: "kids_cybertruck_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Kids Cybertruck Tee",
      gender: "kid",
    },
    {
      description:
        "The refreshed Kids Racing Stripe Tee is made from 100% Peruvian cotton, featuring a newly enhanced racing stripe with a brushed Tesla wordmark that's perfect for any speed racer.",
      images: ["8529354-00-A_0_2000.jpg", "8529354-00-A_1.jpg"],
      inStock: 10,
      price: 30,
      sizes: ["XS", "S", "M"],
      slug: "kids_racing_stripe_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Kids Racing Stripe Tee",
      gender: "kid",
    },
    {
      description:
        "Designed for fit, comfort and style, the Tesla T Logo Tee is made from 100% Peruvian cotton and features a silicone-printed T Logo on the left chest.",
      images: ["7652465-00-A_0_2000.jpg", "7652465-00-A_1.jpg"],
      inStock: 10,
      price: 30,
      sizes: ["XS", "S", "M"],
      slug: "kids_3d_t_logo_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Kids 3D T Logo Tee",
      gender: "kid",
    },
    {
      description:
        "The checkered tee is made from long grain, GMO free Peruvian cotton. Peru is the only country in the world where cotton is picked by hand on a large scale. The 4,500-year-old tradition prevents damage to the fiber during the picking process and removes the need to use chemicals to open the cotton plants before harvest. This environmentally friendly process results in cotton that is soft, strong, and lustrous – and the tee will get even softer with every wash.",
      images: ["100042307_0_2000.jpg", "100042307_alt_2000.jpg"],
      inStock: 10,
      price: 30,
      sizes: ["XS", "S", "M"],
      slug: "kids_checkered_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Kids Checkered Tee",
      gender: "kid",
    },
    {
      description:
        "For the future space traveler with discerning taste, a soft, cotton onesie with snap closure bottom. Clear labeling provided in case of contact with a new spacefaring civilization. 100% Cotton. Made in Peru",
      images: ["1473809-00-A_1_2000.jpg", "1473809-00-A_alt.jpg"],
      inStock: 16,
      price: 25,
      sizes: ["XS", "S"],
      slug: "made_on_earth_by_humans_onesie",
      type: "shirts",
      tags: ["shirt"],
      title: "Made on Earth by Humans Onesie",
      gender: "kid",
    },
    {
      description:
        "The Kids Scribble T Logo Onesie is made from 100% Peruvian cotton and features a Tesla T sketched logo for every little artist to wear.",
      images: ["8529387-00-A_0_2000.jpg", "8529387-00-A_1.jpg"],
      inStock: 0,
      price: 30,
      sizes: ["XS", "S"],
      slug: "scribble_t_logo_onesie",
      type: "shirts",
      tags: ["shirt"],
      title: "Scribble T Logo Onesie",
      gender: "kid",
    },
    {
      description:
        "Muestre su compromiso con la energía sostenible con este atrevido mono para su pequeño. Nota: No evita las emisiones. 100% algodón. Hecho en Paraguay.",
      images: ["1473834-00-A_2_2000.jpg", "1473829-00-A_2_2000.jpg"],
      inStock: 10,
      price: 30,
      sizes: ["XS", "S"],
      slug: "mono_casi_cero_emisiones",
      type: "shirts",
      tags: ["shirt"],
      title: "Mono (casi) cero emisiones",
      gender: "kid",
    },
    {
      description:
        "Wear your Kids Cyberquad Bomber Jacket during your adventures on Cyberquad for Kids. The bomber jacket features a graffiti-style illustration of our Cyberquad silhouette and wordmark. With three zippered pockets and our signature T logo and Tesla wordmark printed along the sleeves, Kids Cyberquad Bomber Jacket is perfect for wherever the trail takes you. Made from 60% cotton and 40% polyester.",
      images: ["1742702-00-A_0_2000.jpg", "1742702-00-A_1.jpg"],
      inStock: 10,
      price: 65,
      sizes: ["XS", "S", "M"],
      slug: "kids_cyberquad_bomber_jacket",
      type: "shirts",
      tags: ["shirt"],
      title: "Kids Cyberquad Bomber Jacket",
      gender: "kid",
    },
    {
      description:
        "Cruise the playground in style with the Kids Corp Jacket. Modeled after the original Tesla Corp Jacket, the Kids Corp Jacket features the same understated style and high-quality materials but at a pint-sized scale.",
      images: ["1506211-00-A_0_2000.jpg", "1506211-00-A_1_2000.jpg"],
      inStock: 10,
      price: 30,
      sizes: ["XS", "S", "M"],
      slug: "kids_corp_jacket",
      type: "shirts",
      tags: ["shirt"],
      title: "Kids Corp Jacket",
      gender: "kid",
    },
  ],
};
